// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: apm_planner.proto

package com.heinemann.grpc.apmplanner;

public final class ApmPlanner {
  private ApmPlanner() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface NullOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.heinemann.grpc.apmplanner.Null)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code com.heinemann.grpc.apmplanner.Null}
   */
  public  static final class Null extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.heinemann.grpc.apmplanner.Null)
      NullOrBuilder {
    // Use Null.newBuilder() to construct.
    private Null(com.google.protobuf.GeneratedMessage.Builder builder) {
      super(builder);
    }
    private Null() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Null(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(
            new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this));
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.heinemann.grpc.apmplanner.ApmPlanner.internal_static_com_heinemann_grpc_apmplanner_Null_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.heinemann.grpc.apmplanner.ApmPlanner.internal_static_com_heinemann_grpc_apmplanner_Null_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.heinemann.grpc.apmplanner.ApmPlanner.Null.class, com.heinemann.grpc.apmplanner.ApmPlanner.Null.Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static com.heinemann.grpc.apmplanner.ApmPlanner.Null parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.heinemann.grpc.apmplanner.ApmPlanner.Null parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.heinemann.grpc.apmplanner.ApmPlanner.Null parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.heinemann.grpc.apmplanner.ApmPlanner.Null parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.heinemann.grpc.apmplanner.ApmPlanner.Null parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.heinemann.grpc.apmplanner.ApmPlanner.Null parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.heinemann.grpc.apmplanner.ApmPlanner.Null parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.heinemann.grpc.apmplanner.ApmPlanner.Null parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.heinemann.grpc.apmplanner.ApmPlanner.Null parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.heinemann.grpc.apmplanner.ApmPlanner.Null parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.heinemann.grpc.apmplanner.ApmPlanner.Null prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.heinemann.grpc.apmplanner.Null}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.heinemann.grpc.apmplanner.Null)
        com.heinemann.grpc.apmplanner.ApmPlanner.NullOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.heinemann.grpc.apmplanner.ApmPlanner.internal_static_com_heinemann_grpc_apmplanner_Null_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.heinemann.grpc.apmplanner.ApmPlanner.internal_static_com_heinemann_grpc_apmplanner_Null_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.heinemann.grpc.apmplanner.ApmPlanner.Null.class, com.heinemann.grpc.apmplanner.ApmPlanner.Null.Builder.class);
      }

      // Construct using com.heinemann.grpc.apmplanner.ApmPlanner.Null.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.heinemann.grpc.apmplanner.ApmPlanner.internal_static_com_heinemann_grpc_apmplanner_Null_descriptor;
      }

      public com.heinemann.grpc.apmplanner.ApmPlanner.Null getDefaultInstanceForType() {
        return com.heinemann.grpc.apmplanner.ApmPlanner.Null.getDefaultInstance();
      }

      public com.heinemann.grpc.apmplanner.ApmPlanner.Null build() {
        com.heinemann.grpc.apmplanner.ApmPlanner.Null result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.heinemann.grpc.apmplanner.ApmPlanner.Null buildPartial() {
        com.heinemann.grpc.apmplanner.ApmPlanner.Null result = new com.heinemann.grpc.apmplanner.ApmPlanner.Null(this);
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.heinemann.grpc.apmplanner.ApmPlanner.Null) {
          return mergeFrom((com.heinemann.grpc.apmplanner.ApmPlanner.Null)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.heinemann.grpc.apmplanner.ApmPlanner.Null other) {
        if (other == com.heinemann.grpc.apmplanner.ApmPlanner.Null.getDefaultInstance()) return this;
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.heinemann.grpc.apmplanner.ApmPlanner.Null parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.heinemann.grpc.apmplanner.ApmPlanner.Null) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:com.heinemann.grpc.apmplanner.Null)
    }

    // @@protoc_insertion_point(class_scope:com.heinemann.grpc.apmplanner.Null)
    private static final com.heinemann.grpc.apmplanner.ApmPlanner.Null DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.heinemann.grpc.apmplanner.ApmPlanner.Null();
    }

    public static com.heinemann.grpc.apmplanner.ApmPlanner.Null getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    public static final com.google.protobuf.Parser<Null> PARSER =
        new com.google.protobuf.AbstractParser<Null>() {
      public Null parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new Null(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Null> getParserForType() {
      return PARSER;
    }

    public com.heinemann.grpc.apmplanner.ApmPlanner.Null getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface UASOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.heinemann.grpc.apmplanner.UAS)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 identifier = 1;</code>
     */
    int getIdentifier();
  }
  /**
   * Protobuf type {@code com.heinemann.grpc.apmplanner.UAS}
   */
  public  static final class UAS extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.heinemann.grpc.apmplanner.UAS)
      UASOrBuilder {
    // Use UAS.newBuilder() to construct.
    private UAS(com.google.protobuf.GeneratedMessage.Builder builder) {
      super(builder);
    }
    private UAS() {
      identifier_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private UAS(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              identifier_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(
            new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this));
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.heinemann.grpc.apmplanner.ApmPlanner.internal_static_com_heinemann_grpc_apmplanner_UAS_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.heinemann.grpc.apmplanner.ApmPlanner.internal_static_com_heinemann_grpc_apmplanner_UAS_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.heinemann.grpc.apmplanner.ApmPlanner.UAS.class, com.heinemann.grpc.apmplanner.ApmPlanner.UAS.Builder.class);
    }

    public static final int IDENTIFIER_FIELD_NUMBER = 1;
    private int identifier_;
    /**
     * <code>optional int32 identifier = 1;</code>
     */
    public int getIdentifier() {
      return identifier_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (identifier_ != 0) {
        output.writeInt32(1, identifier_);
      }
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (identifier_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, identifier_);
      }
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static com.heinemann.grpc.apmplanner.ApmPlanner.UAS parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.heinemann.grpc.apmplanner.ApmPlanner.UAS parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.heinemann.grpc.apmplanner.ApmPlanner.UAS parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.heinemann.grpc.apmplanner.ApmPlanner.UAS parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.heinemann.grpc.apmplanner.ApmPlanner.UAS parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.heinemann.grpc.apmplanner.ApmPlanner.UAS parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.heinemann.grpc.apmplanner.ApmPlanner.UAS parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.heinemann.grpc.apmplanner.ApmPlanner.UAS parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.heinemann.grpc.apmplanner.ApmPlanner.UAS parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.heinemann.grpc.apmplanner.ApmPlanner.UAS parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.heinemann.grpc.apmplanner.ApmPlanner.UAS prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.heinemann.grpc.apmplanner.UAS}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.heinemann.grpc.apmplanner.UAS)
        com.heinemann.grpc.apmplanner.ApmPlanner.UASOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.heinemann.grpc.apmplanner.ApmPlanner.internal_static_com_heinemann_grpc_apmplanner_UAS_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.heinemann.grpc.apmplanner.ApmPlanner.internal_static_com_heinemann_grpc_apmplanner_UAS_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.heinemann.grpc.apmplanner.ApmPlanner.UAS.class, com.heinemann.grpc.apmplanner.ApmPlanner.UAS.Builder.class);
      }

      // Construct using com.heinemann.grpc.apmplanner.ApmPlanner.UAS.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        identifier_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.heinemann.grpc.apmplanner.ApmPlanner.internal_static_com_heinemann_grpc_apmplanner_UAS_descriptor;
      }

      public com.heinemann.grpc.apmplanner.ApmPlanner.UAS getDefaultInstanceForType() {
        return com.heinemann.grpc.apmplanner.ApmPlanner.UAS.getDefaultInstance();
      }

      public com.heinemann.grpc.apmplanner.ApmPlanner.UAS build() {
        com.heinemann.grpc.apmplanner.ApmPlanner.UAS result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.heinemann.grpc.apmplanner.ApmPlanner.UAS buildPartial() {
        com.heinemann.grpc.apmplanner.ApmPlanner.UAS result = new com.heinemann.grpc.apmplanner.ApmPlanner.UAS(this);
        result.identifier_ = identifier_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.heinemann.grpc.apmplanner.ApmPlanner.UAS) {
          return mergeFrom((com.heinemann.grpc.apmplanner.ApmPlanner.UAS)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.heinemann.grpc.apmplanner.ApmPlanner.UAS other) {
        if (other == com.heinemann.grpc.apmplanner.ApmPlanner.UAS.getDefaultInstance()) return this;
        if (other.getIdentifier() != 0) {
          setIdentifier(other.getIdentifier());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.heinemann.grpc.apmplanner.ApmPlanner.UAS parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.heinemann.grpc.apmplanner.ApmPlanner.UAS) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int identifier_ ;
      /**
       * <code>optional int32 identifier = 1;</code>
       */
      public int getIdentifier() {
        return identifier_;
      }
      /**
       * <code>optional int32 identifier = 1;</code>
       */
      public Builder setIdentifier(int value) {
        
        identifier_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 identifier = 1;</code>
       */
      public Builder clearIdentifier() {
        
        identifier_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:com.heinemann.grpc.apmplanner.UAS)
    }

    // @@protoc_insertion_point(class_scope:com.heinemann.grpc.apmplanner.UAS)
    private static final com.heinemann.grpc.apmplanner.ApmPlanner.UAS DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.heinemann.grpc.apmplanner.ApmPlanner.UAS();
    }

    public static com.heinemann.grpc.apmplanner.ApmPlanner.UAS getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    public static final com.google.protobuf.Parser<UAS> PARSER =
        new com.google.protobuf.AbstractParser<UAS>() {
      public UAS parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new UAS(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<UAS> getParserForType() {
      return PARSER;
    }

    public com.heinemann.grpc.apmplanner.ApmPlanner.UAS getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_heinemann_grpc_apmplanner_Null_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_heinemann_grpc_apmplanner_Null_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_heinemann_grpc_apmplanner_UAS_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_heinemann_grpc_apmplanner_UAS_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021apm_planner.proto\022\035com.heinemann.grpc." +
      "apmplanner\"\006\n\004Null\"\031\n\003UAS\022\022\n\nidentifier\030" +
      "\001 \001(\0052g\n\nUASManager\022Y\n\014GetActiveUAS\022#.co" +
      "m.heinemann.grpc.apmplanner.Null\032\".com.h" +
      "einemann.grpc.apmplanner.UAS\"\000B,\n\035com.he" +
      "inemann.grpc.apmplanner\242\002\nAPMPlannerb\006pr" +
      "oto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_heinemann_grpc_apmplanner_Null_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_heinemann_grpc_apmplanner_Null_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_heinemann_grpc_apmplanner_Null_descriptor,
        new java.lang.String[] { });
    internal_static_com_heinemann_grpc_apmplanner_UAS_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_heinemann_grpc_apmplanner_UAS_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_heinemann_grpc_apmplanner_UAS_descriptor,
        new java.lang.String[] { "Identifier", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
