// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: apm_planner.proto

package com.heinemann.grpc.apmplanner;

public final class ApmPlanner {
  private ApmPlanner() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface NullOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.heinemann.grpc.apmplanner.Null)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code com.heinemann.grpc.apmplanner.Null}
   */
  public  static final class Null extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.heinemann.grpc.apmplanner.Null)
      NullOrBuilder {
    // Use Null.newBuilder() to construct.
    private Null(com.google.protobuf.GeneratedMessage.Builder builder) {
      super(builder);
    }
    private Null() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Null(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(
            new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this));
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.heinemann.grpc.apmplanner.ApmPlanner.internal_static_com_heinemann_grpc_apmplanner_Null_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.heinemann.grpc.apmplanner.ApmPlanner.internal_static_com_heinemann_grpc_apmplanner_Null_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.heinemann.grpc.apmplanner.ApmPlanner.Null.class, com.heinemann.grpc.apmplanner.ApmPlanner.Null.Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static com.heinemann.grpc.apmplanner.ApmPlanner.Null parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.heinemann.grpc.apmplanner.ApmPlanner.Null parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.heinemann.grpc.apmplanner.ApmPlanner.Null parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.heinemann.grpc.apmplanner.ApmPlanner.Null parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.heinemann.grpc.apmplanner.ApmPlanner.Null parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.heinemann.grpc.apmplanner.ApmPlanner.Null parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.heinemann.grpc.apmplanner.ApmPlanner.Null parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.heinemann.grpc.apmplanner.ApmPlanner.Null parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.heinemann.grpc.apmplanner.ApmPlanner.Null parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.heinemann.grpc.apmplanner.ApmPlanner.Null parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.heinemann.grpc.apmplanner.ApmPlanner.Null prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.heinemann.grpc.apmplanner.Null}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.heinemann.grpc.apmplanner.Null)
        com.heinemann.grpc.apmplanner.ApmPlanner.NullOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.heinemann.grpc.apmplanner.ApmPlanner.internal_static_com_heinemann_grpc_apmplanner_Null_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.heinemann.grpc.apmplanner.ApmPlanner.internal_static_com_heinemann_grpc_apmplanner_Null_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.heinemann.grpc.apmplanner.ApmPlanner.Null.class, com.heinemann.grpc.apmplanner.ApmPlanner.Null.Builder.class);
      }

      // Construct using com.heinemann.grpc.apmplanner.ApmPlanner.Null.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.heinemann.grpc.apmplanner.ApmPlanner.internal_static_com_heinemann_grpc_apmplanner_Null_descriptor;
      }

      public com.heinemann.grpc.apmplanner.ApmPlanner.Null getDefaultInstanceForType() {
        return com.heinemann.grpc.apmplanner.ApmPlanner.Null.getDefaultInstance();
      }

      public com.heinemann.grpc.apmplanner.ApmPlanner.Null build() {
        com.heinemann.grpc.apmplanner.ApmPlanner.Null result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.heinemann.grpc.apmplanner.ApmPlanner.Null buildPartial() {
        com.heinemann.grpc.apmplanner.ApmPlanner.Null result = new com.heinemann.grpc.apmplanner.ApmPlanner.Null(this);
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.heinemann.grpc.apmplanner.ApmPlanner.Null) {
          return mergeFrom((com.heinemann.grpc.apmplanner.ApmPlanner.Null)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.heinemann.grpc.apmplanner.ApmPlanner.Null other) {
        if (other == com.heinemann.grpc.apmplanner.ApmPlanner.Null.getDefaultInstance()) return this;
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.heinemann.grpc.apmplanner.ApmPlanner.Null parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.heinemann.grpc.apmplanner.ApmPlanner.Null) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:com.heinemann.grpc.apmplanner.Null)
    }

    // @@protoc_insertion_point(class_scope:com.heinemann.grpc.apmplanner.Null)
    private static final com.heinemann.grpc.apmplanner.ApmPlanner.Null DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.heinemann.grpc.apmplanner.ApmPlanner.Null();
    }

    public static com.heinemann.grpc.apmplanner.ApmPlanner.Null getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    public static final com.google.protobuf.Parser<Null> PARSER =
        new com.google.protobuf.AbstractParser<Null>() {
      public Null parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new Null(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Null> getParserForType() {
      return PARSER;
    }

    public com.heinemann.grpc.apmplanner.ApmPlanner.Null getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface UasIdentifierOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.heinemann.grpc.apmplanner.UasIdentifier)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 identifier = 1;</code>
     */
    int getIdentifier();
  }
  /**
   * Protobuf type {@code com.heinemann.grpc.apmplanner.UasIdentifier}
   */
  public  static final class UasIdentifier extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.heinemann.grpc.apmplanner.UasIdentifier)
      UasIdentifierOrBuilder {
    // Use UasIdentifier.newBuilder() to construct.
    private UasIdentifier(com.google.protobuf.GeneratedMessage.Builder builder) {
      super(builder);
    }
    private UasIdentifier() {
      identifier_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private UasIdentifier(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              identifier_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(
            new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this));
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.heinemann.grpc.apmplanner.ApmPlanner.internal_static_com_heinemann_grpc_apmplanner_UasIdentifier_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.heinemann.grpc.apmplanner.ApmPlanner.internal_static_com_heinemann_grpc_apmplanner_UasIdentifier_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.heinemann.grpc.apmplanner.ApmPlanner.UasIdentifier.class, com.heinemann.grpc.apmplanner.ApmPlanner.UasIdentifier.Builder.class);
    }

    public static final int IDENTIFIER_FIELD_NUMBER = 1;
    private int identifier_;
    /**
     * <code>optional int32 identifier = 1;</code>
     */
    public int getIdentifier() {
      return identifier_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (identifier_ != 0) {
        output.writeInt32(1, identifier_);
      }
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (identifier_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, identifier_);
      }
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static com.heinemann.grpc.apmplanner.ApmPlanner.UasIdentifier parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.heinemann.grpc.apmplanner.ApmPlanner.UasIdentifier parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.heinemann.grpc.apmplanner.ApmPlanner.UasIdentifier parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.heinemann.grpc.apmplanner.ApmPlanner.UasIdentifier parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.heinemann.grpc.apmplanner.ApmPlanner.UasIdentifier parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.heinemann.grpc.apmplanner.ApmPlanner.UasIdentifier parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.heinemann.grpc.apmplanner.ApmPlanner.UasIdentifier parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.heinemann.grpc.apmplanner.ApmPlanner.UasIdentifier parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.heinemann.grpc.apmplanner.ApmPlanner.UasIdentifier parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.heinemann.grpc.apmplanner.ApmPlanner.UasIdentifier parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.heinemann.grpc.apmplanner.ApmPlanner.UasIdentifier prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.heinemann.grpc.apmplanner.UasIdentifier}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.heinemann.grpc.apmplanner.UasIdentifier)
        com.heinemann.grpc.apmplanner.ApmPlanner.UasIdentifierOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.heinemann.grpc.apmplanner.ApmPlanner.internal_static_com_heinemann_grpc_apmplanner_UasIdentifier_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.heinemann.grpc.apmplanner.ApmPlanner.internal_static_com_heinemann_grpc_apmplanner_UasIdentifier_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.heinemann.grpc.apmplanner.ApmPlanner.UasIdentifier.class, com.heinemann.grpc.apmplanner.ApmPlanner.UasIdentifier.Builder.class);
      }

      // Construct using com.heinemann.grpc.apmplanner.ApmPlanner.UasIdentifier.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        identifier_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.heinemann.grpc.apmplanner.ApmPlanner.internal_static_com_heinemann_grpc_apmplanner_UasIdentifier_descriptor;
      }

      public com.heinemann.grpc.apmplanner.ApmPlanner.UasIdentifier getDefaultInstanceForType() {
        return com.heinemann.grpc.apmplanner.ApmPlanner.UasIdentifier.getDefaultInstance();
      }

      public com.heinemann.grpc.apmplanner.ApmPlanner.UasIdentifier build() {
        com.heinemann.grpc.apmplanner.ApmPlanner.UasIdentifier result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.heinemann.grpc.apmplanner.ApmPlanner.UasIdentifier buildPartial() {
        com.heinemann.grpc.apmplanner.ApmPlanner.UasIdentifier result = new com.heinemann.grpc.apmplanner.ApmPlanner.UasIdentifier(this);
        result.identifier_ = identifier_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.heinemann.grpc.apmplanner.ApmPlanner.UasIdentifier) {
          return mergeFrom((com.heinemann.grpc.apmplanner.ApmPlanner.UasIdentifier)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.heinemann.grpc.apmplanner.ApmPlanner.UasIdentifier other) {
        if (other == com.heinemann.grpc.apmplanner.ApmPlanner.UasIdentifier.getDefaultInstance()) return this;
        if (other.getIdentifier() != 0) {
          setIdentifier(other.getIdentifier());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.heinemann.grpc.apmplanner.ApmPlanner.UasIdentifier parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.heinemann.grpc.apmplanner.ApmPlanner.UasIdentifier) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int identifier_ ;
      /**
       * <code>optional int32 identifier = 1;</code>
       */
      public int getIdentifier() {
        return identifier_;
      }
      /**
       * <code>optional int32 identifier = 1;</code>
       */
      public Builder setIdentifier(int value) {
        
        identifier_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 identifier = 1;</code>
       */
      public Builder clearIdentifier() {
        
        identifier_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:com.heinemann.grpc.apmplanner.UasIdentifier)
    }

    // @@protoc_insertion_point(class_scope:com.heinemann.grpc.apmplanner.UasIdentifier)
    private static final com.heinemann.grpc.apmplanner.ApmPlanner.UasIdentifier DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.heinemann.grpc.apmplanner.ApmPlanner.UasIdentifier();
    }

    public static com.heinemann.grpc.apmplanner.ApmPlanner.UasIdentifier getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    public static final com.google.protobuf.Parser<UasIdentifier> PARSER =
        new com.google.protobuf.AbstractParser<UasIdentifier>() {
      public UasIdentifier parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new UasIdentifier(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<UasIdentifier> getParserForType() {
      return PARSER;
    }

    public com.heinemann.grpc.apmplanner.ApmPlanner.UasIdentifier getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface UasModeOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.heinemann.grpc.apmplanner.UasMode)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 mode = 1;</code>
     */
    int getMode();
  }
  /**
   * Protobuf type {@code com.heinemann.grpc.apmplanner.UasMode}
   */
  public  static final class UasMode extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.heinemann.grpc.apmplanner.UasMode)
      UasModeOrBuilder {
    // Use UasMode.newBuilder() to construct.
    private UasMode(com.google.protobuf.GeneratedMessage.Builder builder) {
      super(builder);
    }
    private UasMode() {
      mode_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private UasMode(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              mode_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(
            new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this));
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.heinemann.grpc.apmplanner.ApmPlanner.internal_static_com_heinemann_grpc_apmplanner_UasMode_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.heinemann.grpc.apmplanner.ApmPlanner.internal_static_com_heinemann_grpc_apmplanner_UasMode_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.heinemann.grpc.apmplanner.ApmPlanner.UasMode.class, com.heinemann.grpc.apmplanner.ApmPlanner.UasMode.Builder.class);
    }

    public static final int MODE_FIELD_NUMBER = 1;
    private int mode_;
    /**
     * <code>optional int32 mode = 1;</code>
     */
    public int getMode() {
      return mode_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (mode_ != 0) {
        output.writeInt32(1, mode_);
      }
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (mode_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, mode_);
      }
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static com.heinemann.grpc.apmplanner.ApmPlanner.UasMode parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.heinemann.grpc.apmplanner.ApmPlanner.UasMode parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.heinemann.grpc.apmplanner.ApmPlanner.UasMode parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.heinemann.grpc.apmplanner.ApmPlanner.UasMode parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.heinemann.grpc.apmplanner.ApmPlanner.UasMode parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.heinemann.grpc.apmplanner.ApmPlanner.UasMode parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.heinemann.grpc.apmplanner.ApmPlanner.UasMode parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.heinemann.grpc.apmplanner.ApmPlanner.UasMode parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.heinemann.grpc.apmplanner.ApmPlanner.UasMode parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.heinemann.grpc.apmplanner.ApmPlanner.UasMode parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.heinemann.grpc.apmplanner.ApmPlanner.UasMode prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.heinemann.grpc.apmplanner.UasMode}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.heinemann.grpc.apmplanner.UasMode)
        com.heinemann.grpc.apmplanner.ApmPlanner.UasModeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.heinemann.grpc.apmplanner.ApmPlanner.internal_static_com_heinemann_grpc_apmplanner_UasMode_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.heinemann.grpc.apmplanner.ApmPlanner.internal_static_com_heinemann_grpc_apmplanner_UasMode_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.heinemann.grpc.apmplanner.ApmPlanner.UasMode.class, com.heinemann.grpc.apmplanner.ApmPlanner.UasMode.Builder.class);
      }

      // Construct using com.heinemann.grpc.apmplanner.ApmPlanner.UasMode.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        mode_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.heinemann.grpc.apmplanner.ApmPlanner.internal_static_com_heinemann_grpc_apmplanner_UasMode_descriptor;
      }

      public com.heinemann.grpc.apmplanner.ApmPlanner.UasMode getDefaultInstanceForType() {
        return com.heinemann.grpc.apmplanner.ApmPlanner.UasMode.getDefaultInstance();
      }

      public com.heinemann.grpc.apmplanner.ApmPlanner.UasMode build() {
        com.heinemann.grpc.apmplanner.ApmPlanner.UasMode result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.heinemann.grpc.apmplanner.ApmPlanner.UasMode buildPartial() {
        com.heinemann.grpc.apmplanner.ApmPlanner.UasMode result = new com.heinemann.grpc.apmplanner.ApmPlanner.UasMode(this);
        result.mode_ = mode_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.heinemann.grpc.apmplanner.ApmPlanner.UasMode) {
          return mergeFrom((com.heinemann.grpc.apmplanner.ApmPlanner.UasMode)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.heinemann.grpc.apmplanner.ApmPlanner.UasMode other) {
        if (other == com.heinemann.grpc.apmplanner.ApmPlanner.UasMode.getDefaultInstance()) return this;
        if (other.getMode() != 0) {
          setMode(other.getMode());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.heinemann.grpc.apmplanner.ApmPlanner.UasMode parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.heinemann.grpc.apmplanner.ApmPlanner.UasMode) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int mode_ ;
      /**
       * <code>optional int32 mode = 1;</code>
       */
      public int getMode() {
        return mode_;
      }
      /**
       * <code>optional int32 mode = 1;</code>
       */
      public Builder setMode(int value) {
        
        mode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 mode = 1;</code>
       */
      public Builder clearMode() {
        
        mode_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:com.heinemann.grpc.apmplanner.UasMode)
    }

    // @@protoc_insertion_point(class_scope:com.heinemann.grpc.apmplanner.UasMode)
    private static final com.heinemann.grpc.apmplanner.ApmPlanner.UasMode DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.heinemann.grpc.apmplanner.ApmPlanner.UasMode();
    }

    public static com.heinemann.grpc.apmplanner.ApmPlanner.UasMode getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    public static final com.google.protobuf.Parser<UasMode> PARSER =
        new com.google.protobuf.AbstractParser<UasMode>() {
      public UasMode parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new UasMode(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<UasMode> getParserForType() {
      return PARSER;
    }

    public com.heinemann.grpc.apmplanner.ApmPlanner.UasMode getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface UasOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.heinemann.grpc.apmplanner.Uas)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 identifier = 1;</code>
     */
    int getIdentifier();

    /**
     * <code>optional string name = 2;</code>
     */
    java.lang.String getName();
    /**
     * <code>optional string name = 2;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>optional string systemTypeName = 3;</code>
     */
    java.lang.String getSystemTypeName();
    /**
     * <code>optional string systemTypeName = 3;</code>
     */
    com.google.protobuf.ByteString
        getSystemTypeNameBytes();

    /**
     * <code>optional string autopilotTypeName = 4;</code>
     */
    java.lang.String getAutopilotTypeName();
    /**
     * <code>optional string autopilotTypeName = 4;</code>
     */
    com.google.protobuf.ByteString
        getAutopilotTypeNameBytes();

    /**
     * <code>optional string shortState = 5;</code>
     */
    java.lang.String getShortState();
    /**
     * <code>optional string shortState = 5;</code>
     */
    com.google.protobuf.ByteString
        getShortStateBytes();

    /**
     * <code>optional string shortMode = 6;</code>
     */
    java.lang.String getShortMode();
    /**
     * <code>optional string shortMode = 6;</code>
     */
    com.google.protobuf.ByteString
        getShortModeBytes();

    /**
     * <code>optional bool isArmed = 7;</code>
     */
    boolean getIsArmed();

    /**
     * <code>optional string batterySpecs = 8;</code>
     */
    java.lang.String getBatterySpecs();
    /**
     * <code>optional string batterySpecs = 8;</code>
     */
    com.google.protobuf.ByteString
        getBatterySpecsBytes();

    /**
     * <code>optional int64 uptime = 9;</code>
     */
    long getUptime();

    /**
     * <code>optional double roll = 10;</code>
     */
    double getRoll();

    /**
     * <code>optional double pitch = 11;</code>
     */
    double getPitch();

    /**
     * <code>optional double yaw = 12;</code>
     */
    double getYaw();
  }
  /**
   * Protobuf type {@code com.heinemann.grpc.apmplanner.Uas}
   */
  public  static final class Uas extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.heinemann.grpc.apmplanner.Uas)
      UasOrBuilder {
    // Use Uas.newBuilder() to construct.
    private Uas(com.google.protobuf.GeneratedMessage.Builder builder) {
      super(builder);
    }
    private Uas() {
      identifier_ = 0;
      name_ = "";
      systemTypeName_ = "";
      autopilotTypeName_ = "";
      shortState_ = "";
      shortMode_ = "";
      isArmed_ = false;
      batterySpecs_ = "";
      uptime_ = 0L;
      roll_ = 0D;
      pitch_ = 0D;
      yaw_ = 0D;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Uas(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              identifier_ = input.readInt32();
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();

              name_ = bs;
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();

              systemTypeName_ = bs;
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();

              autopilotTypeName_ = bs;
              break;
            }
            case 42: {
              com.google.protobuf.ByteString bs = input.readBytes();

              shortState_ = bs;
              break;
            }
            case 50: {
              com.google.protobuf.ByteString bs = input.readBytes();

              shortMode_ = bs;
              break;
            }
            case 56: {

              isArmed_ = input.readBool();
              break;
            }
            case 66: {
              com.google.protobuf.ByteString bs = input.readBytes();

              batterySpecs_ = bs;
              break;
            }
            case 72: {

              uptime_ = input.readInt64();
              break;
            }
            case 81: {

              roll_ = input.readDouble();
              break;
            }
            case 89: {

              pitch_ = input.readDouble();
              break;
            }
            case 97: {

              yaw_ = input.readDouble();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(
            new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this));
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.heinemann.grpc.apmplanner.ApmPlanner.internal_static_com_heinemann_grpc_apmplanner_Uas_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.heinemann.grpc.apmplanner.ApmPlanner.internal_static_com_heinemann_grpc_apmplanner_Uas_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.heinemann.grpc.apmplanner.ApmPlanner.Uas.class, com.heinemann.grpc.apmplanner.ApmPlanner.Uas.Builder.class);
    }

    public static final int IDENTIFIER_FIELD_NUMBER = 1;
    private int identifier_;
    /**
     * <code>optional int32 identifier = 1;</code>
     */
    public int getIdentifier() {
      return identifier_;
    }

    public static final int NAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object name_;
    /**
     * <code>optional string name = 2;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SYSTEMTYPENAME_FIELD_NUMBER = 3;
    private volatile java.lang.Object systemTypeName_;
    /**
     * <code>optional string systemTypeName = 3;</code>
     */
    public java.lang.String getSystemTypeName() {
      java.lang.Object ref = systemTypeName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          systemTypeName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string systemTypeName = 3;</code>
     */
    public com.google.protobuf.ByteString
        getSystemTypeNameBytes() {
      java.lang.Object ref = systemTypeName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        systemTypeName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int AUTOPILOTTYPENAME_FIELD_NUMBER = 4;
    private volatile java.lang.Object autopilotTypeName_;
    /**
     * <code>optional string autopilotTypeName = 4;</code>
     */
    public java.lang.String getAutopilotTypeName() {
      java.lang.Object ref = autopilotTypeName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          autopilotTypeName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string autopilotTypeName = 4;</code>
     */
    public com.google.protobuf.ByteString
        getAutopilotTypeNameBytes() {
      java.lang.Object ref = autopilotTypeName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        autopilotTypeName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SHORTSTATE_FIELD_NUMBER = 5;
    private volatile java.lang.Object shortState_;
    /**
     * <code>optional string shortState = 5;</code>
     */
    public java.lang.String getShortState() {
      java.lang.Object ref = shortState_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          shortState_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string shortState = 5;</code>
     */
    public com.google.protobuf.ByteString
        getShortStateBytes() {
      java.lang.Object ref = shortState_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        shortState_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SHORTMODE_FIELD_NUMBER = 6;
    private volatile java.lang.Object shortMode_;
    /**
     * <code>optional string shortMode = 6;</code>
     */
    public java.lang.String getShortMode() {
      java.lang.Object ref = shortMode_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          shortMode_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string shortMode = 6;</code>
     */
    public com.google.protobuf.ByteString
        getShortModeBytes() {
      java.lang.Object ref = shortMode_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        shortMode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ISARMED_FIELD_NUMBER = 7;
    private boolean isArmed_;
    /**
     * <code>optional bool isArmed = 7;</code>
     */
    public boolean getIsArmed() {
      return isArmed_;
    }

    public static final int BATTERYSPECS_FIELD_NUMBER = 8;
    private volatile java.lang.Object batterySpecs_;
    /**
     * <code>optional string batterySpecs = 8;</code>
     */
    public java.lang.String getBatterySpecs() {
      java.lang.Object ref = batterySpecs_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          batterySpecs_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string batterySpecs = 8;</code>
     */
    public com.google.protobuf.ByteString
        getBatterySpecsBytes() {
      java.lang.Object ref = batterySpecs_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        batterySpecs_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int UPTIME_FIELD_NUMBER = 9;
    private long uptime_;
    /**
     * <code>optional int64 uptime = 9;</code>
     */
    public long getUptime() {
      return uptime_;
    }

    public static final int ROLL_FIELD_NUMBER = 10;
    private double roll_;
    /**
     * <code>optional double roll = 10;</code>
     */
    public double getRoll() {
      return roll_;
    }

    public static final int PITCH_FIELD_NUMBER = 11;
    private double pitch_;
    /**
     * <code>optional double pitch = 11;</code>
     */
    public double getPitch() {
      return pitch_;
    }

    public static final int YAW_FIELD_NUMBER = 12;
    private double yaw_;
    /**
     * <code>optional double yaw = 12;</code>
     */
    public double getYaw() {
      return yaw_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (identifier_ != 0) {
        output.writeInt32(1, identifier_);
      }
      if (!getNameBytes().isEmpty()) {
        output.writeBytes(2, getNameBytes());
      }
      if (!getSystemTypeNameBytes().isEmpty()) {
        output.writeBytes(3, getSystemTypeNameBytes());
      }
      if (!getAutopilotTypeNameBytes().isEmpty()) {
        output.writeBytes(4, getAutopilotTypeNameBytes());
      }
      if (!getShortStateBytes().isEmpty()) {
        output.writeBytes(5, getShortStateBytes());
      }
      if (!getShortModeBytes().isEmpty()) {
        output.writeBytes(6, getShortModeBytes());
      }
      if (isArmed_ != false) {
        output.writeBool(7, isArmed_);
      }
      if (!getBatterySpecsBytes().isEmpty()) {
        output.writeBytes(8, getBatterySpecsBytes());
      }
      if (uptime_ != 0L) {
        output.writeInt64(9, uptime_);
      }
      if (roll_ != 0D) {
        output.writeDouble(10, roll_);
      }
      if (pitch_ != 0D) {
        output.writeDouble(11, pitch_);
      }
      if (yaw_ != 0D) {
        output.writeDouble(12, yaw_);
      }
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (identifier_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, identifier_);
      }
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getNameBytes());
      }
      if (!getSystemTypeNameBytes().isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getSystemTypeNameBytes());
      }
      if (!getAutopilotTypeNameBytes().isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getAutopilotTypeNameBytes());
      }
      if (!getShortStateBytes().isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getShortStateBytes());
      }
      if (!getShortModeBytes().isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, getShortModeBytes());
      }
      if (isArmed_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(7, isArmed_);
      }
      if (!getBatterySpecsBytes().isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(8, getBatterySpecsBytes());
      }
      if (uptime_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(9, uptime_);
      }
      if (roll_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(10, roll_);
      }
      if (pitch_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(11, pitch_);
      }
      if (yaw_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(12, yaw_);
      }
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static com.heinemann.grpc.apmplanner.ApmPlanner.Uas parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.heinemann.grpc.apmplanner.ApmPlanner.Uas parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.heinemann.grpc.apmplanner.ApmPlanner.Uas parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.heinemann.grpc.apmplanner.ApmPlanner.Uas parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.heinemann.grpc.apmplanner.ApmPlanner.Uas parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.heinemann.grpc.apmplanner.ApmPlanner.Uas parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.heinemann.grpc.apmplanner.ApmPlanner.Uas parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.heinemann.grpc.apmplanner.ApmPlanner.Uas parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.heinemann.grpc.apmplanner.ApmPlanner.Uas parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.heinemann.grpc.apmplanner.ApmPlanner.Uas parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.heinemann.grpc.apmplanner.ApmPlanner.Uas prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.heinemann.grpc.apmplanner.Uas}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.heinemann.grpc.apmplanner.Uas)
        com.heinemann.grpc.apmplanner.ApmPlanner.UasOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.heinemann.grpc.apmplanner.ApmPlanner.internal_static_com_heinemann_grpc_apmplanner_Uas_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.heinemann.grpc.apmplanner.ApmPlanner.internal_static_com_heinemann_grpc_apmplanner_Uas_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.heinemann.grpc.apmplanner.ApmPlanner.Uas.class, com.heinemann.grpc.apmplanner.ApmPlanner.Uas.Builder.class);
      }

      // Construct using com.heinemann.grpc.apmplanner.ApmPlanner.Uas.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        identifier_ = 0;

        name_ = "";

        systemTypeName_ = "";

        autopilotTypeName_ = "";

        shortState_ = "";

        shortMode_ = "";

        isArmed_ = false;

        batterySpecs_ = "";

        uptime_ = 0L;

        roll_ = 0D;

        pitch_ = 0D;

        yaw_ = 0D;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.heinemann.grpc.apmplanner.ApmPlanner.internal_static_com_heinemann_grpc_apmplanner_Uas_descriptor;
      }

      public com.heinemann.grpc.apmplanner.ApmPlanner.Uas getDefaultInstanceForType() {
        return com.heinemann.grpc.apmplanner.ApmPlanner.Uas.getDefaultInstance();
      }

      public com.heinemann.grpc.apmplanner.ApmPlanner.Uas build() {
        com.heinemann.grpc.apmplanner.ApmPlanner.Uas result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.heinemann.grpc.apmplanner.ApmPlanner.Uas buildPartial() {
        com.heinemann.grpc.apmplanner.ApmPlanner.Uas result = new com.heinemann.grpc.apmplanner.ApmPlanner.Uas(this);
        result.identifier_ = identifier_;
        result.name_ = name_;
        result.systemTypeName_ = systemTypeName_;
        result.autopilotTypeName_ = autopilotTypeName_;
        result.shortState_ = shortState_;
        result.shortMode_ = shortMode_;
        result.isArmed_ = isArmed_;
        result.batterySpecs_ = batterySpecs_;
        result.uptime_ = uptime_;
        result.roll_ = roll_;
        result.pitch_ = pitch_;
        result.yaw_ = yaw_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.heinemann.grpc.apmplanner.ApmPlanner.Uas) {
          return mergeFrom((com.heinemann.grpc.apmplanner.ApmPlanner.Uas)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.heinemann.grpc.apmplanner.ApmPlanner.Uas other) {
        if (other == com.heinemann.grpc.apmplanner.ApmPlanner.Uas.getDefaultInstance()) return this;
        if (other.getIdentifier() != 0) {
          setIdentifier(other.getIdentifier());
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (!other.getSystemTypeName().isEmpty()) {
          systemTypeName_ = other.systemTypeName_;
          onChanged();
        }
        if (!other.getAutopilotTypeName().isEmpty()) {
          autopilotTypeName_ = other.autopilotTypeName_;
          onChanged();
        }
        if (!other.getShortState().isEmpty()) {
          shortState_ = other.shortState_;
          onChanged();
        }
        if (!other.getShortMode().isEmpty()) {
          shortMode_ = other.shortMode_;
          onChanged();
        }
        if (other.getIsArmed() != false) {
          setIsArmed(other.getIsArmed());
        }
        if (!other.getBatterySpecs().isEmpty()) {
          batterySpecs_ = other.batterySpecs_;
          onChanged();
        }
        if (other.getUptime() != 0L) {
          setUptime(other.getUptime());
        }
        if (other.getRoll() != 0D) {
          setRoll(other.getRoll());
        }
        if (other.getPitch() != 0D) {
          setPitch(other.getPitch());
        }
        if (other.getYaw() != 0D) {
          setYaw(other.getYaw());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.heinemann.grpc.apmplanner.ApmPlanner.Uas parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.heinemann.grpc.apmplanner.ApmPlanner.Uas) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int identifier_ ;
      /**
       * <code>optional int32 identifier = 1;</code>
       */
      public int getIdentifier() {
        return identifier_;
      }
      /**
       * <code>optional int32 identifier = 1;</code>
       */
      public Builder setIdentifier(int value) {
        
        identifier_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 identifier = 1;</code>
       */
      public Builder clearIdentifier() {
        
        identifier_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>optional string name = 2;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            name_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string name = 2;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string name = 2;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 2;</code>
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 2;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object systemTypeName_ = "";
      /**
       * <code>optional string systemTypeName = 3;</code>
       */
      public java.lang.String getSystemTypeName() {
        java.lang.Object ref = systemTypeName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            systemTypeName_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string systemTypeName = 3;</code>
       */
      public com.google.protobuf.ByteString
          getSystemTypeNameBytes() {
        java.lang.Object ref = systemTypeName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          systemTypeName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string systemTypeName = 3;</code>
       */
      public Builder setSystemTypeName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        systemTypeName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string systemTypeName = 3;</code>
       */
      public Builder clearSystemTypeName() {
        
        systemTypeName_ = getDefaultInstance().getSystemTypeName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string systemTypeName = 3;</code>
       */
      public Builder setSystemTypeNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        systemTypeName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object autopilotTypeName_ = "";
      /**
       * <code>optional string autopilotTypeName = 4;</code>
       */
      public java.lang.String getAutopilotTypeName() {
        java.lang.Object ref = autopilotTypeName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            autopilotTypeName_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string autopilotTypeName = 4;</code>
       */
      public com.google.protobuf.ByteString
          getAutopilotTypeNameBytes() {
        java.lang.Object ref = autopilotTypeName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          autopilotTypeName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string autopilotTypeName = 4;</code>
       */
      public Builder setAutopilotTypeName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        autopilotTypeName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string autopilotTypeName = 4;</code>
       */
      public Builder clearAutopilotTypeName() {
        
        autopilotTypeName_ = getDefaultInstance().getAutopilotTypeName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string autopilotTypeName = 4;</code>
       */
      public Builder setAutopilotTypeNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        autopilotTypeName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object shortState_ = "";
      /**
       * <code>optional string shortState = 5;</code>
       */
      public java.lang.String getShortState() {
        java.lang.Object ref = shortState_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            shortState_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string shortState = 5;</code>
       */
      public com.google.protobuf.ByteString
          getShortStateBytes() {
        java.lang.Object ref = shortState_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          shortState_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string shortState = 5;</code>
       */
      public Builder setShortState(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        shortState_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string shortState = 5;</code>
       */
      public Builder clearShortState() {
        
        shortState_ = getDefaultInstance().getShortState();
        onChanged();
        return this;
      }
      /**
       * <code>optional string shortState = 5;</code>
       */
      public Builder setShortStateBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        shortState_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object shortMode_ = "";
      /**
       * <code>optional string shortMode = 6;</code>
       */
      public java.lang.String getShortMode() {
        java.lang.Object ref = shortMode_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            shortMode_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string shortMode = 6;</code>
       */
      public com.google.protobuf.ByteString
          getShortModeBytes() {
        java.lang.Object ref = shortMode_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          shortMode_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string shortMode = 6;</code>
       */
      public Builder setShortMode(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        shortMode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string shortMode = 6;</code>
       */
      public Builder clearShortMode() {
        
        shortMode_ = getDefaultInstance().getShortMode();
        onChanged();
        return this;
      }
      /**
       * <code>optional string shortMode = 6;</code>
       */
      public Builder setShortModeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        shortMode_ = value;
        onChanged();
        return this;
      }

      private boolean isArmed_ ;
      /**
       * <code>optional bool isArmed = 7;</code>
       */
      public boolean getIsArmed() {
        return isArmed_;
      }
      /**
       * <code>optional bool isArmed = 7;</code>
       */
      public Builder setIsArmed(boolean value) {
        
        isArmed_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool isArmed = 7;</code>
       */
      public Builder clearIsArmed() {
        
        isArmed_ = false;
        onChanged();
        return this;
      }

      private java.lang.Object batterySpecs_ = "";
      /**
       * <code>optional string batterySpecs = 8;</code>
       */
      public java.lang.String getBatterySpecs() {
        java.lang.Object ref = batterySpecs_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            batterySpecs_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string batterySpecs = 8;</code>
       */
      public com.google.protobuf.ByteString
          getBatterySpecsBytes() {
        java.lang.Object ref = batterySpecs_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          batterySpecs_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string batterySpecs = 8;</code>
       */
      public Builder setBatterySpecs(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        batterySpecs_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string batterySpecs = 8;</code>
       */
      public Builder clearBatterySpecs() {
        
        batterySpecs_ = getDefaultInstance().getBatterySpecs();
        onChanged();
        return this;
      }
      /**
       * <code>optional string batterySpecs = 8;</code>
       */
      public Builder setBatterySpecsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        batterySpecs_ = value;
        onChanged();
        return this;
      }

      private long uptime_ ;
      /**
       * <code>optional int64 uptime = 9;</code>
       */
      public long getUptime() {
        return uptime_;
      }
      /**
       * <code>optional int64 uptime = 9;</code>
       */
      public Builder setUptime(long value) {
        
        uptime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 uptime = 9;</code>
       */
      public Builder clearUptime() {
        
        uptime_ = 0L;
        onChanged();
        return this;
      }

      private double roll_ ;
      /**
       * <code>optional double roll = 10;</code>
       */
      public double getRoll() {
        return roll_;
      }
      /**
       * <code>optional double roll = 10;</code>
       */
      public Builder setRoll(double value) {
        
        roll_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional double roll = 10;</code>
       */
      public Builder clearRoll() {
        
        roll_ = 0D;
        onChanged();
        return this;
      }

      private double pitch_ ;
      /**
       * <code>optional double pitch = 11;</code>
       */
      public double getPitch() {
        return pitch_;
      }
      /**
       * <code>optional double pitch = 11;</code>
       */
      public Builder setPitch(double value) {
        
        pitch_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional double pitch = 11;</code>
       */
      public Builder clearPitch() {
        
        pitch_ = 0D;
        onChanged();
        return this;
      }

      private double yaw_ ;
      /**
       * <code>optional double yaw = 12;</code>
       */
      public double getYaw() {
        return yaw_;
      }
      /**
       * <code>optional double yaw = 12;</code>
       */
      public Builder setYaw(double value) {
        
        yaw_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional double yaw = 12;</code>
       */
      public Builder clearYaw() {
        
        yaw_ = 0D;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:com.heinemann.grpc.apmplanner.Uas)
    }

    // @@protoc_insertion_point(class_scope:com.heinemann.grpc.apmplanner.Uas)
    private static final com.heinemann.grpc.apmplanner.ApmPlanner.Uas DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.heinemann.grpc.apmplanner.ApmPlanner.Uas();
    }

    public static com.heinemann.grpc.apmplanner.ApmPlanner.Uas getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    public static final com.google.protobuf.Parser<Uas> PARSER =
        new com.google.protobuf.AbstractParser<Uas>() {
      public Uas parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new Uas(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Uas> getParserForType() {
      return PARSER;
    }

    public com.heinemann.grpc.apmplanner.ApmPlanner.Uas getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_heinemann_grpc_apmplanner_Null_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_heinemann_grpc_apmplanner_Null_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_heinemann_grpc_apmplanner_UasIdentifier_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_heinemann_grpc_apmplanner_UasIdentifier_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_heinemann_grpc_apmplanner_UasMode_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_heinemann_grpc_apmplanner_UasMode_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_heinemann_grpc_apmplanner_Uas_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_heinemann_grpc_apmplanner_Uas_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021apm_planner.proto\022\035com.heinemann.grpc." +
      "apmplanner\"\006\n\004Null\"#\n\rUasIdentifier\022\022\n\ni" +
      "dentifier\030\001 \001(\005\"\027\n\007UasMode\022\014\n\004mode\030\001 \001(\005" +
      "\"\342\001\n\003Uas\022\022\n\nidentifier\030\001 \001(\005\022\014\n\004name\030\002 \001" +
      "(\t\022\026\n\016systemTypeName\030\003 \001(\t\022\031\n\021autopilotT" +
      "ypeName\030\004 \001(\t\022\022\n\nshortState\030\005 \001(\t\022\021\n\tsho" +
      "rtMode\030\006 \001(\t\022\017\n\007isArmed\030\007 \001(\010\022\024\n\014battery" +
      "Specs\030\010 \001(\t\022\016\n\006uptime\030\t \001(\003\022\014\n\004roll\030\n \001(" +
      "\001\022\r\n\005pitch\030\013 \001(\001\022\013\n\003yaw\030\014 \001(\0012\277\004\n\nUasMan" +
      "ager\022c\n\014getActiveUas\022#.com.heinemann.grp",
      "c.apmplanner.Null\032,.com.heinemann.grpc.a" +
      "pmplanner.UasIdentifier\"\000\022c\n\014setActiveUa" +
      "s\022,.com.heinemann.grpc.apmplanner.UasIde" +
      "ntifier\032#.com.heinemann.grpc.apmplanner." +
      "Null\"\000\022\\\n\006getUas\022,.com.heinemann.grpc.ap" +
      "mplanner.UasIdentifier\032\".com.heinemann.g" +
      "rpc.apmplanner.Uas\"\000\022Y\n\ngetUasList\022#.com" +
      ".heinemann.grpc.apmplanner.Null\032\".com.he" +
      "inemann.grpc.apmplanner.Uas\"\0000\001\022T\n\006reboo" +
      "t\022#.com.heinemann.grpc.apmplanner.Null\032#",
      ".com.heinemann.grpc.apmplanner.Null\"\000\022X\n" +
      "\007setMode\022&.com.heinemann.grpc.apmplanner" +
      ".UasMode\032#.com.heinemann.grpc.apmplanner" +
      ".Null\"\000B,\n\035com.heinemann.grpc.apmplanner" +
      "\242\002\nAPMPlannerb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_heinemann_grpc_apmplanner_Null_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_heinemann_grpc_apmplanner_Null_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_heinemann_grpc_apmplanner_Null_descriptor,
        new java.lang.String[] { });
    internal_static_com_heinemann_grpc_apmplanner_UasIdentifier_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_heinemann_grpc_apmplanner_UasIdentifier_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_heinemann_grpc_apmplanner_UasIdentifier_descriptor,
        new java.lang.String[] { "Identifier", });
    internal_static_com_heinemann_grpc_apmplanner_UasMode_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_heinemann_grpc_apmplanner_UasMode_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_heinemann_grpc_apmplanner_UasMode_descriptor,
        new java.lang.String[] { "Mode", });
    internal_static_com_heinemann_grpc_apmplanner_Uas_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_heinemann_grpc_apmplanner_Uas_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_heinemann_grpc_apmplanner_Uas_descriptor,
        new java.lang.String[] { "Identifier", "Name", "SystemTypeName", "AutopilotTypeName", "ShortState", "ShortMode", "IsArmed", "BatterySpecs", "Uptime", "Roll", "Pitch", "Yaw", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
